### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by mheiber** [evanw/zeroscript#15]
Thanks for sharing this work! Do you plan to continue working on Thinscript?

**Comment by nidin** [comment]
@mheiber I have forked and re-created TurboScript http://01alchemist.com/projects/turboscript/playground/

**Comment by affixalex** [comment]
Just wanted to chime in and say that ThinScript is awesome! I'd love to see more work on it.

When DOM manipulation becomes possible, this will become VERY cool.

**Comment by nidin** [comment]
@hypoalex This project seems dead, I am working on a fork of thinscript https://github.com/01alchemist/turboscript there is no DOM manipulation in my near roadmap instead preparing for adding shared memory and SIMD since my aim is speed, speed and speed

**Comment by jslegers** [comment]
@nidin :

How compatible is TurboScript supposed to be with TypeScript? 

Or to put it differently : is any TurboScript valid TypeScript? Can I use TypeScript to process my TurboScript  and convert it to normal JavaScript (if I would want that for some reason)? And if not, what are the differences between TurboScript and TypeScript that I would need to consider?

**Comment by nidin** [comment]
@jslegers TurboScript will not be a valid TypeScript. In order to move forward I need to leave typescript behind. Also there is no sign from TypeScript team to support WebAssembly. Soon I will introduce multi-threading and SIMD features in TurboScript when WebAssembly spec finalize, this will introduce new syntax in TurboScript which will not be compatible with TypeScript. As I explained in another comment, I have a plan to compile part of TurboScript to normal JavaScript but that is further down on the road-map.

**Comment by jslegers** [comment]
Yeah... It looks like both the TypeScript team at Microsoft & the Flow team as Facebook see their projects as mere type checking tools. I'd say that's pretty shortsighted of them. If only they saw the potential that you and I are seeing in TypeScript-to-WebAssembly compilation...

**Comment by mindplay-dk** [comment]
FYI, there is now [AssemblyScript](https://github.com/AssemblyScript/assemblyscript), which is active - doesn’t look like TurboScript is still going (?)
