### ISSUE TITLE
Darn Good

### ISSUE THREAD

**Issue by RobertoMalatesta** [evanw/zeroscript#5]
No real ish listed in this message here.

Only a few 2c suggestions:

keep the language as thin and clear as possible:
- at first do not implement a GC (then, maybe)
- the lang should be as near as possible to typescript or some other language that already has intellisense plugins in editors like atom or vsc

make it a blockbuster:
- see if you can integrate a basic WebGL/OpenGL backend on top of which a standard GUI system can be implemented
- shared memory thread support , since JS/WASM/C are already there
- socket/comm support

I know these things heavily depend on WASM evolution path but having a single source code that can be compiled/transpiled into native applications for desktop,mobile,web is ... well... :-D

Keep on with this nice piece of work.

Rob

(I will follow this project for sure and see if I can somehow be of help).

**Comment by evanw** [comment]
You read my mind :)

My plan is to implement something similar to the ES6 module system to make it really easy for the community to build packages on top of. Then this project won't be as much about WebGL/OpenGL as it will be about providing a solid compiler and language to build on. I'll definitely take a stab at making a cross-platform GPU/GUI system package but this way the ecosystem will let the best implementation rise to the top.

I'm planning on keeping the language as close to TypeScript as is reasonable, but also sprinkling in design decisions from C# when it makes sense (examples: integer types, preprocessor, operator overloading, struct vs class, etc.). I'm also planning on creating my own "intellisense" plugins eventually since IDE support is important to me. It's a lot of work of course but I've [done it before](https://github.com/evanw/glslx-vscode) so I know what I'm getting into.

As far as memory management it looks like reference counting is a good fit, especially for mobile. Weak pointers are really inelegant though so I'm strongly considering adding a cycle collector on top, sort of like how Python works. Weak pointers get pretty confusing with complex data structures and nested lambdas and stuff. But yeah it'll come later after an initial reference counting implementation lands.

**Comment by RobertoMalatesta** [comment]
Hi @evanw,
thanks for the insights (btw I did not know you were the author of some of the most awesome webgl demos at the time  of writing)

Some considerations & questions:

What about sockets and threads? webasm will definitely help.

> > As far as memory management it looks like reference counting is a good fit, especially for mobile

20+ years of STW or convoluted garbage collectors took out some myth from autoGC.

> > I'm planning on keeping the language as close to TypeScript 

What about converting your compiler into a tsc wrap-on to allow, say:
      "target": "WASM", in tsconfig.json then?   

-- RM

**Comment by nippur72** [comment]
also, why not output to TypeScript directly instead of JavaScript ?

**Comment by evanw** [comment]
Good questions. I don't think it makes sense to cross-compile TypeScript directly to WASM for reasons outlined here: https://news.ycombinator.com/item?id=11384801. Basically TypeScript is too optimized around JavaScript development for efficient ahead-of-time compilation to native code. I do plan to output to TypeScript/ES6 but I want to get the language itself working first. I'm not sure what you mean around sockets/threads. Also the initial version of WASM is not going to support shared-memory threading, so there's no way to experiment with that right now for the WASM target.

**Comment by RobertoMalatesta** [comment]
> >  I'm not sure what you mean around sockets/threads.

Implementing constructs for threads and sockets should be easy since
memory mapping IO, Unix like IOCTL and sockets are part of the specification

TS --> WASM
TS is a very good language and fixing a few tidbits (basically the ones you mentioned in the YNews you cited) it could be a universal language for portable desktop and mobile  apps as well
true today TS is geared toward JS but once WASM becomes wildly adopted in major browser I expect MS deal with these things.
Not in a near future since WASM Commitee release cycle is rather slow.

**Comment by trusktr** [comment]
WebGL support would be awesome!
