### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by rumkin** [evanw/zeroscript#6]
Hi, Evan. I'm impressed with this project. I have some thoughts about c-compilant language: meta programming on comments with all this `# if` is very strange and it look's like dinosaur today! Why not to make compilation loops to produce result until all known constants and if statements will not solved. Let me explain:

We have ENV constant which hold target environment, let it be 'BROWSER'. We write an usual if statement:

```
if (ENV == "BROWSER") {
   const MSG="It's a Browser"
}
else if (ENV == "NODEJS") {
   const MSG="it's Node.js" 
}

print(MSG)
```

So the first compilation loop should remove if branches and leave const MSG="It's a Browser". Now we have the second known constant MSG which should be equal to "It's a Browser". And on the second cycle loop print will get MSG value and become `print("It's a Browser")`. On the third loop we see no other links to constant message and remove it. And so we got:

```
print("It's a Browser")
```

So if there is runtime computations in the if statement than it shall not be reduced:

```
if (ENV == "BROWSER" && random() > 0.5) {
   const MSG="It's a Browser"
}
```

There is only one problem with block scoped vars which should be solved somehow. But this code looks more elegant.

**Comment by evanw** [comment]
I agree that the C# preprocessor syntax is ugly, and that a fixed-point iteration over if statements at compile time is a nifty way of doing it. That's why I implemented something exactly like this for the preprocessor in my programming language called [Skew](http://skew-lang.org).

It worked pretty well given how Skew works but a goal of ThinScript is to stay syntactically close to TypeScript for familiarity, which makes the if statement approach much less flexible than a C#-style preprocessor for ThinScript. For example, Skew has open declarations (declarations are all merged together) so it can do something like this in Skew:

```
if TARGET == .CSHARP {
  class ParseError : System.Exception {}
} else if TARGET == .JAVASCRIPT {
  class ParseError : Error {}
} else {
  class ParseError {}
}

class ParseError {
  var line = 0
  var column = 0

  def location string {
    return "line: \(line), column: \(column)"
  }
}
```

Without open declarations, ThinScript would have to copy the entire body of ParseError into each branch of the if statement with this proposal. With a C#-style preprocessor this can be done easily in ThinScript without massive code duplication:

``` TypeScript
class ParseError
#if CSHARP
  extends System.Exception
#elif JAVASCRIPT
  extends Error
#endif
{
  line: int;
  column: int;

  location(): string {
    return `line: ${this.line}, column: ${this.column}`;
  }
}
```

Using a C#-style preprocessor is also faster to compile with and is easier to cache the results of for incremental compilation scenarios, which is another important goal of ThinScript.

That said, the preprocessor is mainly for use with library code and I fully expect most code to use normal if statements exclusively. A big goal of ThinScript is compiler optimization and while it isn't implemented yet, ThinScript will offer full constant folding and dead code elimination so if statements like the ones in your example will be specialized at compile time (assuming `ENV` is a constant of course). You will probably have to use a single variable declaration though:

``` TypeScript
const MSG =
  ENV == "BROWSER" ? "It's a Browser" :
  ENV == "NODEJS" ? "it's Node.js" :
  null;

print(MSG);
```
