### ISSUE TITLE
Wasm Compilator

### ISSUE THREAD

**Issue by rumkin** [evanw/zeroscript#7]
As I see there is inbrowser wasm compilattion. I need pure C to WASM compiler in JS. I'm stuck with binaryen. Can you help me with it?

**Comment by evanw** [comment]
Nope that's not one of the goals of this project, sorry. I'm sure someone will write something like that when WebAssembly comes out though so I would keep an eye out for it.

If you want to do it yourself, the easiest way is probably to start from an existing compiler like [TCC](http://bellard.org/tcc/) and just add a new backend. You could also try to port emscripten to the web but I don't recommend that since LLVM is huge and emscripten is a loose pile of shell scripts, some of which are written in Python. It looks like someone tried to do the LLVM part of this at some point, although it's probably very out of date: https://kripken.github.io/llvm.js/demo.html.
